### PR TITLE
Consistency fixes

### PR DESCRIPTION
**Pull request by RickardNi**
I did some cosistency fixes (mostly capitalizations of words, or vice versa) for the rewritten rulebook, and was asked by @qwrtln to do the same for the mission book.

First of all, thanks for your great work with this mission book. It will for sure be a great addition to this great game, and I hope more are to come.

Second of all, mistakes could have been made here, so please feel free to point them out. Most of the changes are manually made, but some of them were quick "replace all" where I previewed all changes at a glance, but mistakes are likely to have occured at some point.

--

Some of the corrections may seem strange, for instance "scenario" is capitalized everywhere, but the reason for this is to maintain consistency with the rewritten rulebook project. A decision in that project was made to capitalize all game terms, but it can be debated what terms are actual game terms and not just general terms. I have no problem with reverting any capitalizations, but in doing so, I think consistency should be maintained both within the project and with the rulebook project.

Feel free to discuss anything here. Any discussion are sure to contribute to the quality of these projects. Thanks!

### CODE REVIEW

**Comment by qwrtln** [comment]
Thanks. "Random Town" should definitely stay as it was.

**Comment by qwrtln** [comment]
Also, "level" seems to be inconsistent. Hero level is spelled both ways. I guess it should be "Hero Level" and "Level Tracker", but "level III fight"?

**Comment by qwrtln** [comment]
I fixed random town, also reverted changes in dragons lore text.

**Comment by RickardNi** [comment]
Thanks for looking through the changes!

Some comments on the reverts:

1. Regarding "level", I will take another round on this just to make sure everything is consistent. Good point!

2. Reverting the lore text makes sense. Mostly, I tried to avoid making changes there, but these slipped through.

3. "Random Town" was actually intentional. On my list, it is marked as lower-case, which I also think makes some sense, since "random" is a general term rather than a game-term. I'm okay with "Random Town" as well, but that is not how it is in the rulebook. It is consistently lower-case there, with the exception of headlines and start of a new sentance.

4. I actually removed the "for" intentionally for "What to Play" since I thought it sounded better. I recall reading "a game up to 6 players" more often than "a game for up to 6 players", but I guess both are correct, and a quick google found me results for both, so I guess it works as reverted.

**Comment by RickardNi** [comment]
Regarding "level", it should be capitalized on all occurances, as is correct according to my notes, good find.

It is consistent in the rulebook on 62 out of 64 occurances.

**Comment by qwrtln** [comment]
Capitalizing "Level" breaks the layout on two pages. Meh, I need to fix this.

**Comment by qwrtln** [comment]
Another one is "[Dd]eck", which appears both ways, how should it be?

**Comment by RickardNi** [comment]
> Another one is "[Dd]eck", which appears both ways, how should it be?

It should be Deck. I see now that it appears both ways in a lot of places. Probably I missed it or had it in my mind to save it to later and forgot about it. I fix it right away!

**Comment by qwrtln** [comment]
@RickardNi I added a simple check for wrongly capitalized words. For now, it's a rather conservative list of "deck", "field", "hero", "level", and "unit". I don't want to make it too restrictive. It actually found two occurrences of "hero" haha, please check it out. What do you think? Should we expand this list?

**Comment by qwrtln** [comment]
Another one: Tile/tile. Is there a different context for this?

**Review by qwrtln — APPROVED** [review]

**Comment by RickardNi** [comment]
Sorry, I haven't had time to check everything and I've seen you've done a lot of changes. That's great!

I think it's great to have a list in the repository with all the words and game terms, as you seem to have started. Same goes for the rulebook project, and I never got around to "finish" it, though I think every word is a case of its own, which can be debated. There isn't really any decision made, I just took what what already done when I first reviewed the rulebook, which in turn was based on the original rulebook, so some things can really be debated and changed. For instance, why is "Turn" a game term, but "player" not?

Anyway, here is my list that is still in my notes:

**Capitalized**
Action, Activated, Activates, Alliance, Artifact, Attack (attribute, Die), Building Material, Combat, Cooperative, Deck, Defense (action, attribute, Card, Token), Dice, Die, Discard Pile (but not discard), Faction, Faction Cube, Field, Flaggable, Flagging, Gate,	Gold (only the resource), Hero, Initiative, Level, Main Hero, Map Tile*, Mines, Neutral Unit, Obstacles, Population, Power (attribute), Recruited, Reinforce, Revisit, Round, Scenario, Secondary Hero, Settlement, Spell, Statistics, Token, Town, Turn (noun), Unit, Valuables, Visit, Visitable, Wall

*Map Tile was added recently when reading the mission book, so probably Tile should be it instead.

**Lower-Case**
adjacent, active, alternative, attacked (verb), competitive, cost, damage, defeated, defending (verb),	discard (except Discard Pile),
enemy/enemies, expansion, gold (general, not resource), hand, model, inactive, player, protected/protection, random, roll/rolling, turn (verb), unvisited

**Pull request merged**
