### PR TITLE
Make map setup formatting for coop scenarios consistent with official books [re-re-request]

### PR DESCRIPTION
**Pull request by Dima793**
Resolve https://github.com/qwrtln/Homm3BG-mission-book/issues/145
Change "Map setup" section formatting for coop scenarios from "bold text with bullet points" to "just bullet points", to be consistent with how it's done in Archon Studio's official HoMM books.

### CODE REVIEW

**Comment by qwrtln** [comment]
po4a commit

**Comment by qwrtln** [comment]
I think shackles will work. What do you think?

en-08

**Comment by Dima793** [comment]
I lack "sense of beauty" to make judgement on the art 😅 No objections from me.

**Comment by Dima793** [comment]
On an unrelated note, in this PR the "P" for player count on map tile list is not in italic. I don't see a reason for it to be while other symbols next to it (numbers, brackets, "+") are not in italic. 
Thought I should mention it in case you have a stance on it but might've missed it.

**Comment by Dima793** [comment]
> do you agree it's better with the art?

I think it's about the same. The amount of free space doesn't seem too huge for me to seem disturbing, at least in comparison to prior empty space in the second column.

**Comment by qwrtln** [comment]
> On an unrelated note, in this PR the "P" for player count on map tile list is not in italic. I don't see a reason for it to be while other symbols next to it (numbers, brackets, "+") are not in italic. Thought I should mention it in case you have a stance on it but might've missed it.

LaTeX renders those formulas as italics, but in this case we can make an exception and skip it.

**Review by qwrtln — APPROVED** [review]

**Pull request merged**
